- src/main/scala/com/socrata/spandex/Spandex.scala
This fixes a NPE when starting the server (specific to OSX?)
> Change `conf` val to be lazy in main

- spandex-common/src/test/scala/com/socrata/spandex/common/TestESData.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexServlet.scala
- spandex-http/src/test/scala/com/socrata/spandex/http/SpandexServletSpec.scala
+ must send contentType application/json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/spandex/8)
> http tweaks

- spandex-common/src/main/resources/reference.conf
- spandex-common/src/main/scala/com/socrata/spandex/common/client/SpandexElasticSearchClient.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/TestESData.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/client/SpandexElasticSearchClientSpec.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/ResyncHandler.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/RowOpsHandler.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/SpandexSecondary.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/VersionEventsHandler.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/WorkingCopyCreatedHandler.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/SpandexSecondaryLikeSpec.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/VersionEventsHandlerSpec.scala
Implementing first couple of perf improvements we agreed on this morning. The rest are on their way.
> Don't refresh during resync; increase batch size; refresh a bit less during row ops

- spandex-common/src/main/resources/reference.conf
- spandex-common/src/main/scala/com/socrata/spandex/common/client/SpandexElasticSearchClient.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/client/SpandexElasticSearchClientSpec.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexServlet.scala
index and search analyzer is case insensitive.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/spandex/18)
> Case insensitive

- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/ResyncHandler.scala
Was previously batching only within a row, which is not very useful.
> Batch resync inserts properly

- README.md
Thanks again @urmilan!! :heart:
> Add some inchoate notes and changes to the readme

- spandex-common/src/main/scala/com/socrata/spandex/common/client/SpandexElasticSearchClient.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexError.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexServlet.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/package.scala
- spandex-http/src/test/scala/com/socrata/spandex/http/SpandexErrorSpec.scala
- spandex-http/src/test/scala/com/socrata/spandex/http/SpandexServletSpec.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/CopyDropHandler.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/ResyncHandler.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/RowOpsHandler.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/SecondaryEventLogger.scala
+ error messages formatted in json
+ column not found returns http 404
+ little bit of cleanup and style
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/spandex/36)
>  errors in json, column not found -> 404 #35 

- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/ResyncHandler.scala
This fixes the c3p0 error about operating on closed ResultSets.
> Move all the resync request code inside the managed context

- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexServlet.scala
- spandex-http/src/test/scala/com/socrata/spandex/http/SpandexServletSpec.scala
Small fix + more stringent tests that makes me hungry for donuts and coconuts.
> Fix json errors

- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/PublishHandler.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/DatasetLifecycleSimulation.scala
More documentation than a test, the intention is to help folks new to the code understand what secondary events are triggered when you do various ordinary things to a dataset and how that gets reflected in the ES index.
> Dataset lifecycle test

- spandex-http/src/main/scala/ScalatraBootstrap.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexServlet.scala
+ bootstrap client with lazy value 
+ pass client to servlet as lazy parameter
+ log init/term for health and version endpoints
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/spandex/44)
> lazy client, verbose logging

- project/Build.scala
- project/plugins.sbt
- spandex-common/src/main/resources/reference.conf
- spandex-common/src/main/scala/com/socrata/spandex/common/client/SpandexElasticSearchClient.scala
- spandex-common/src/main/scala/com/socrata/spandex/common/client/Stage.scala
- spandex-common/src/test/resources/analysisOff.conf
- spandex-common/src/test/resources/analysisOn.conf
- spandex-common/src/test/scala/com/socrata/spandex/common/AnalyzerTest.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/CompletionAnalyzerSpec.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/KeywordAnalyzerSpec.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/client/SpandexElasticSearchClientSpec.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/client/StageSpec.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexServlet.scala
- spandex-http/src/test/scala/com/socrata/spandex/http/SpandexServletSpec.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/PublishHandler.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/VersionEventsHandler.scala
+ imports copy stage info from soda-fountain-lib
+ queries elasticsearch for the appropriate copy by stage
+ defaults to latest
> accept stage info and query secondary for latest

- spandex-common/src/main/scala/com/socrata/spandex/common/client/SpandexElasticSearchClient.scala
- spandex-http/docker/Dockerfile
- spandex-http/docker/README.md
- spandex-http/docker/spandex-http.conf.j2
> docker configurable index/alias

- project/Build.scala
- project/plugins.sbt
- spandex-common/src/main/scala/com/socrata/spandex/common/SpandexBootstrap.scala
- spandex-common/src/main/scala/com/socrata/spandex/common/client/ResponseExtensions.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/AnalyzerTest.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/CompletionAnalyzerSpec.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/KeywordAnalyzerSpec.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/client/TestESClient.scala
- spandex-http/src/main/scala/ScalatraBootstrap.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexResult.scala
- spandex-http/src/main/scala/com/socrata/spandex/http/SpandexServlet.scala
- spandex-http/src/test/scala/com/socrata/spandex/http/SpandexServletSpec.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/DatasetLifecycleSimulation.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/SpandexSecondaryLikeSpec.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/VersionEventsHandlerSpec.scala
https://socrata.atlassian.net/browse/CATALOG-160
use query string parameter to transmit suggestion text
also updated socrata-sbt-plugins and replaced any instances of JavaConversions
> CATALOG-160 use query string parameter to transmit suggestion text

- project/Build.scala
- spandex-common/src/main/scala/com/socrata/spandex/common/client/SpandexElasticSearchClient.scala
- spandex-common/src/test/scala/com/socrata/spandex/common/client/TestESClient.scala
delete by query is now deprecated, recommendation is to use search-scan and bulk request, done.
> elasticsearch 1.7.2

- project/Build.scala
- spandex-secondary/docker/Dockerfile
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/SpandexSecondary.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/VersionEventsHandler.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/DatasetLifecycleSimulation.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/SpandexSecondaryLikeSpec.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/VersionEventsHandlerSpec.scala
Thinking about this more, I think that the spandex secondary jar needs to be updated and rebuilt. The rebuild of the jar needs to go with a rebuild of secondary watcher. 
edit: Actually needs to go before secondary watcher.
> EN-158: Update to new version of datacoordinator.

- project/Build.scala
- spandex-secondary/docker/Dockerfile
Update to fixed version of secondary-watcher
> EN-4304: Update secondary-watcher docker image

- project/Build.scala
- spandex-secondary/docker/Dockerfile
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/SpandexSecondary.scala
- spandex-secondary/src/test/scala/com/socrata/spandex/secondary/SpandexSecondaryLikeSpec.scala
Update secondary-watcher docker image
Update secondary-lib version (removes unused code)
> EN-4323: Use fixed version of secondary-watcher

- elasticsearch-snapshotter/docker/ship.d/snapshot.sh
See the official docs for how this works:
https://github.com/elastic/elasticsearch-cloud-aws/tree/v2.7.1/#version-271-for-elasticsearch-17
> EN-9206: use server-side encryption when uploading to S3

- README.md
Fix sql statement for `secondary_stores_config` for spandex.
> EN-19092: Update docs for spandex

- .gitignore
- .solo/spandex-http.json
- .solo/spandex-secondary.json
- spandex-secondary/docker/ship.d/run
> EN-25528: update solo configs

- project/Build.scala
- spandex-secondary/src/main/scala/com.socrata.spandex.secondary/VersionEventsHandler.scala
> EN-27852 Bump DC version for new computation strategy add/drop events
